### ISSUE TITLE
Delete item in cart

### ISSUE THREAD

**Issue by robov** [pistol88/yii2-cart#14]
When I delete 1 item in the cart, the entire card is dynamically removed (screen is empty)
Only after a reload the items that are still in the cart are displayed again

**Comment by pistol88** [comment]
Look at network console, have a 500 errors?

**Comment by robov** [comment]
no errors

**Comment by pistol88** [comment]
I have no ideas.
Try debug it yourself.

**Comment by robov** [comment]
I skipped using this and use the elementsview instead
