### ISSUE TITLE
ElementList

### ISSUE THREAD

**Issue by robov** [pistol88/yii2-cart#15]
This looks like a nice widget, but the columns are commented out...
Can you fix this so it resembles the hemp rows ?

**Comment by pistol88** [comment]
Not understand, sorry)) Rows are in view file.

**Comment by halumein** [comment]
it was refactored to use viewFile (or custom view) against hardcoded template to render each element in cart list
for example you can use your custom view file:

ElementsList::widget([
'elementView' => '@frontend/views/customViews/cartElementView',
]);

here:
 \vendor\pistol88\yii2-cart\widgets\views\elementListRow.php copied to @frontend/views/customViews/cartElementView.php

then you can modify it as you need.
