### ISSUE TITLE
TAX

### ISSUE THREAD

**Issue by robov** [pistol88/yii2-cart#16]
I see there is no possiblity to show / calculate tax per item per country yet
Every item can their own VAT %
Every country sets their own VAT levels.. so if I order from teh US I need to pay a different VAT than if I order from Europe

**Comment by pistol88** [comment]
I think It's not module's logic, its logic of you application/
Just subscribe to event 'EVENT_ELEMENT_COST ' from config and change the price as you want.

```
'components' => [
    'cart' => [
        //...
        'on element_cost' => function($event) {
            $event->cost = $event->cost*0.1;
        }
    ],
    //...
]
```

**Comment by robov** [comment]
Tax is a separate line
Price = 100
Tax = 5% = 5
Total = 105

However if the customer fills in on the checkout that his country is NL
Then
Price = 100
Tax = 21% = 21
Total = 121
So your solution does not work. There needs to be a separete call and calculation in the JS to add the tax based on the country of checkout

**Comment by pistol88** [comment]
Anyway, I think it's not cart's logic. Its logic fo over module 'tax' or you own application. Yo can connect tax and cart with triggers in JS and PHP component. May have to create new widget CartWithTaxToal, but not in this module.

**Comment by mazurva** [comment]
If support taxes to make similar savings (discount) through behavior?

**Comment by robov** [comment]
Yes taxes behavior is similar
But
Price 100
Discount 80
Total = 20
Tax = 21% = 4.2
Total - 24.2

**Comment by mazurva** [comment]
I'm not sure it will all work as I wrote it now, but as an example.
Config file:
```php
'cart' => [
            'class' => 'pistol88\cart\Cart',
            //...
            'as discount' => [
                'class' => 'app\behaviors\Tax',
                'persent' => 21,
            ],
        ],
```
Sample Tax behavior:
```php
<?php
namespace app\behaviors;
use yii\base\Behavior;
use pistol88\cart\Cart;
class Tax extends Behavior
{
    public $persent = 0;
    public function events()
    {
        return [
            Cart::EVENT_CART_COST => 'doTax'
        ];
    }
    public function doTax($event)
    {
        if($this->persent > 0 && $this->persent <= 100 && $event->cost > 0) {
            $event->cost = $event->cost+($event->cost*$this->persent)/100;
        }
        return $this;
    }
}
```

**Comment by mazurva** [comment]
@pistol88 I can add the behavior for taxes as an example in the module?

**Comment by mazurva** [comment]
To support variable rate tax, you can enable receiving it from the form in his behavior. For example:
```php
public function doTax($event)
    {
        if($this->persent > 0 && $this->persent <= 100 && $event->cost > 0) {
            $event->cost = $event->cost+($event->cost*(int)Yii::app()->request->getParam('persent', $this->persent))/100;
        }
        return $this;
    }
```
Where `$this->persent` using only like default value.

**Comment by mazurva** [comment]
Or you can use session variable, and change it via AJAX

**Comment by robov** [comment]
Though ajax is the nicest solution.. it updates the totals just as it updates the totals when I increase the count

**Comment by robov** [comment]
Seems like a viable solution
1) But I will loose the discount option (as it is reused for tax)
2) How can I pass the tax rate to the behavior ?

**Comment by pistol88** [comment]
>  I can add the behavior for taxes as an example in the module?
Да, будет круто. На выходных переработаем JS, сделаем его менее хардкодным.

**Comment by robov** [comment]
Yes... cool...
