### ISSUE TITLE
Overwrite

### ISSUE THREAD

**Issue by robov** [pistol88/yii2-cart#17]
I though to solve my problems I could just download the package (outside in composer) and integrate and modify it.
However, then I get a cannot instantiate sercive CartService.

**Comment by pistol88** [comment]
Look at bootstrap.php

**Comment by robov** [comment]
the line that seems to be causing the problem is
`    public function __construct(interfaces\CartService $cartService, interfaces\ElementService $elementService, $config = [])`
( in cart/Cart.php )

I copied your package to common\vendor_mod\cart
In my connon\config\bootstrap i have added
`Yii::setAlias('pistol88/cart', dirname(dirname(__DIR__)) . '/common/vendor_mod/cart');`

Any ideas ?

**Comment by robov** [comment]
It is triggered by this call in my cart
$elements = yii::$app->cart->elements;

**Comment by pistol88** [comment]
Add

```
        yii::$container->set('pistol88\cart\interfaces\CartService', 'pistol88\cart\models\Cart');
        yii::$container->set('pistol88\cart\interfaces\ElementService', 'pistol88\cart\models\CartElement');
        yii::$container->set('cartElement', 'pistol88\cart\models\CartElement');
```

To your index.php or config.

**Comment by robov** [comment]
When I add this to 
Frontend\web\index.php or common\config\main.php

The error is still there:
```
Not instantiable – yii\di\NotInstantiableException
Can not instantiate pistol88\cart\interfaces\CartService.

```

**Comment by pistol88** [comment]
add 

```
"autoload": {
    "psr-4": {
        "pistol88\\cart\\": "common/vendor_mod/cart"
    }
}
```

to composer.json and execute "composer update"

**Comment by robov** [comment]
Brilliant !!! thank you su much
Adding that to composer &
Adding the lines to frontend/web/index.php
made it work
