### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by ApXaHgheJI** [pistol88/yii2-cart#2]
А зачем нужен parent_id ? у меня сразу с ним возникла ошибка ... так как он всегда у меня NULL... подправил базу что бы пропускал NULL.
И еще есть метод PUT у компонента - почему не сделать сразу UPDATE(id,Element) и DELETE(id)

**Comment by pistol88** [comment]
parent_id - для сложных корзин. Например, к пицце в корзину докупаются ингредиенты. Это было зачато, но не реализовано до конца. Сделал в миграции поле необязательным, спасибо!

Сервисом элементов служит обычная AR модель. То есть правильнее удалять и обновлять примерно так:

yii::$app->cart->getElementById(1)->delete();
yii::$app->cart->getElementById(1)->loadData()->save();

Правда, работает ли - нужно еще проверить ;)

**Comment by ApXaHgheJI** [comment]
ага - понятно - ну хорошо.
пойду дальше мучать корзину... 
ПСЫ - переделываю под себя корзину ( dropdown ) господи сколько там дивов - пока разберешься что бы свой диз натянуть - можно мозгом поехать - разбить бы как-то или перевести на шаблон ... потому что наверное часа 2 потратил на это....

еще раз спасибо ;)

**Comment by pistol88** [comment]
Виджеты не заточены под переделку - это да, нужно продумать расширяемость.

**Comment by ApXaHgheJI** [comment]
Прости вопрос возник - есть ли возможность на кнопку BUY "BuyButton" widget

**Comment by pistol88** [comment]
> есть ли возможность на кнопку BUY "BuyButton" widget

wat? :)

**Comment by ApXaHgheJI** [comment]
Блин я думал я удалил - забей ) все путем -)
