### ISSUE TITLE
Very slow cart query

### ISSUE THREAD

**Issue by TurningTide** [pistol88/yii2-cart#27]
In my case, query 
`SELECT * FROM `cart` WHERE `user_id`=1` takes around 60-100ms
This is realy slow because field user_id has both user ids and hashes of sessions.
Only solution to fix that is to split sessions and ids in different columns so it could be possible to make indexes for them.

**Comment by pistol88** [comment]
Yes, I do it. Thanks.
And add a limit 1.

**Comment by pistol88** [comment]
Did it here: https://github.com/dvizh/yii2-cart
