### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by robov** [pistol88/yii2-cart#7]
It looks like you created an awesome extension, unfortunately I do not speak russian. Can you please make the documentation in English ?

**Comment by pistol88** [comment]
My English is not very well. Wait pull request with translate from community :) Now.. use google translate :(

**Comment by robov** [comment]
I understand... but your english is FAAAR !! better than my russian ;-)

**Comment by pistol88** [comment]
One of contributers plan do it at sunday.
