### ISSUE TITLE
/cart/element/create 404 (Not Found)

### ISSUE THREAD

**Issue by robov** [pistol88/yii2-cart#8]
When I press the buy button  I get
/cart/element/create 404 (Not Found)

Any Ideas ?

**Comment by pistol88** [comment]
Show this part of code, where generate this link. Or you just go to url in browser?

**Comment by robov** [comment]
```
$product = ProductDescription::findOne(1);
echo BuyButton::widget([
    'model' => $product ,
    'text' => 'Buy',
    'htmlTag' => 'a',
    'cssClass' => 'btn primary'
]);
```

```

**Comment by robov** [comment]
`POST https://dev.xxxxxxxxxx.com/cart/element/create 404 (Not Found)`

**Comment by robov** [comment]
I probably need to add a rule to my urlmanager something like 

> 'cart'=>'pistol88/cart', 
????

**Comment by robov** [comment]
If I do that then the site.com/cart actually shows a page
However the element/create on the press of the button is still not working

**Comment by pistol88** [comment]
You add cart to 'modules' section at config?

**Comment by halumein** [comment]
You don't have to add any rules. Check that you have activate module in frontend/config/main.php (for advanced template) or app/config/web (basic template). In 'modules' section.

**Comment by robov** [comment]
Yes modules were in the main... I just noticed when debugging when resaving the elementcontroller... not it does find it
